export const SEARCH_EXAMS_REQUEST = 'SEARCH_EXAMS_REQUEST';
export const SEARCH_EXAMS_SUCCESS = 'SEARCH_EXAMS_SUCCESS';
export const SEARCH_EXAMS_FAILURE = 'SEARCH_EXAMS_FAILURE';

// Define action types for calendar
export const FETCH_GOVT_EXAMS_CALENDAR_REQUEST = 'FETCH_GOVT_EXAMS_CALENDAR_REQUEST';
export const FETCH_GOVT_EXAMS_CALENDAR_SUCCESS = 'FETCH_GOVT_EXAMS_CALENDAR_SUCCESS';
export const FETCH_GOVT_EXAMS_CALENDAR_FAILURE = 'FETCH_GOVT_EXAMS_CALENDAR_FAILURE';